# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='last_updated',
        ),
    ]
